import type { Character } from "@/lib/types";
import { IMAGES } from "./images";

const W = IMAGES.works;

export const characters: Character[] = [
  {
    slug: "ana-er-han",
    name: "阿娜尔罕",
    workSlug: "ana-er-han",
    workTitle: "阿娜尔罕",
    year: 2013,
    image: W["ana-er-han"],
    description: "南疆姑娘，出道首部电视剧女主角，在民族风情与革命叙事中展现坚韧品格。",
    featured: true,
  },
  {
    slug: "bai-fengjiu",
    name: "白凤九",
    workSlug: "sannshengsanshi-shili-taohua",
    workTitle: "三生三世十里桃花",
    year: 2017,
    image: W["sannshengsanshi-shili-taohua"],
    quote: "追夫三万年，痴情不改。",
    description: "青丘帝姬，灵动痴情，是无数人心中的「九尾小狐狸」；续篇故事见《枕上书》条目。",
    featured: true,
  },
  {
    slug: "qiao-jingjing",
    name: "乔晶晶",
    workSlug: "ni-shi-wo-de-rongyao",
    workTitle: "你是我的荣耀",
    year: 2021,
    image: W["ni-shi-wo-de-rongyao"],
    quote: "我已经跑向你了，这一次你可以慢慢走。",
    description: "顶流女明星，外柔内刚，与航天工程师于途的重逢之恋，国民甜剧经典女主。",
    featured: true,
  },
  {
    slug: "li-changge",
    name: "李长歌",
    workSlug: "chang-ge-xing",
    workTitle: "长歌行",
    year: 2021,
    image: W["chang-ge-xing"],
    quote: "我要守护的，是我所信之道。",
    description: "大唐郡主，智谋与气节兼备，于家国动荡中成长，飒爽大女主代表。",
    featured: true,
  },
  {
    slug: "deng-yan",
    name: "邓妍",
    workSlug: "li-jian-mei-gui",
    workTitle: "利剑·玫瑰",
    year: 2025,
    image: W["li-jian-mei-gui"],
    description: "一线女警，现实打拐题材中的坚韧与温度，展现现实主义表演新高度。",
    featured: true,
  },
  {
    slug: "ji-yunhe",
    name: "纪云禾",
    workSlug: "yu-jiao-ji",
    workTitle: "与君初相识",
    year: 2022,
    image: W["yu-jiao-ji"],
    quote: "愿我所爱之人，余生平安。",
    description: "驭鲛人，隐忍坚韧，于爱恨交织中完成成长与救赎。",
    featured: true,
  },
  {
    slug: "an-ni",
    name: "安旎",
    workSlug: "gong-su",
    workTitle: "公诉",
    year: 2023,
    image: W["gong-su"],
    description: "检察官，现实法治题材转型之作，专业飒爽的女性公诉人形象。",
  },
  {
    slug: "gao-wen",
    name: "高雯",
    workSlug: "ke-la-lian-ren",
    workTitle: "克拉恋人",
    year: 2015,
    image: W["ke-la-lian-ren"],
    description: "明艳张扬的珠宝设计师，「女二出圈」的经典角色，打开知名度的重要一步。",
  },
  {
    slug: "fu-qu",
    name: "芙蕖",
    workSlug: "gu-jian-qi-tan",
    workTitle: "古剑奇谭",
    year: 2014,
    image: W["gu-jian-qi-tan"],
    description: "天墉城女弟子，温柔善良、灵气初显，是迪丽热巴早期古装剧角色之一。",
  },
  {
    slug: "wu-an-po",
    name: "吴安珀",
    workSlug: "wei-shi-dai",
    workTitle: "微时代",
    year: 2014,
    image: W["wei-shi-dai"],
    description: "博翰大学校花，于新媒体时代的青春群像中经历爱情与成长，是签约嘉行后早期网络剧角色。",
  },
  {
    slug: "li-ji",
    name: "骊姬",
    workSlug: "feng-zhong-qiyuan",
    workTitle: "风中奇缘",
    year: 2014,
    image: W["feng-zhong-qiyuan"],
    description: "西域女子，于《大漠谣》改编的史诗叙事中短暂亮相，展现早期异域古装气质。",
  },
  {
    slug: "qing-cheng",
    name: "倾城",
    workSlug: "mei-ren-zhi-zao",
    workTitle: "美人制造",
    year: 2014,
    image: W["mei-ren-zhi-zao"],
    description: "李旦爱妃，唐装造型惊艳亮相的早期古装客串角色。",
  },
  {
    slug: "an-xin",
    name: "安心",
    workSlug: "ban-shu-chuan-qi",
    workTitle: "班淑传奇",
    year: 2015,
    image: W["ban-shu-chuan-qi"],
    description: "楼兰王女，于宫学比试中展现异域风情与灵动气质。",
  },
  {
    slug: "li-huizhen",
    name: "李慧珍",
    workSlug: "piaoliang-de-li-huizhen",
    workTitle: "漂亮的李慧珍",
    year: 2017,
    image: W["piaoliang-de-li-huizhen"],
    description: "平凡女孩逆袭成长的励志女主，是其首部担纲女一号的都市剧。",
  },
  {
    slug: "lie-ruge",
    name: "烈如歌",
    workSlug: "lie-huo-ru-ge",
    workTitle: "烈火如歌",
    year: 2018,
    image: W["lie-huo-ru-ge"],
    description: "侠肝义胆的江湖少女，于恩怨与情感中诠释洒脱与深情。",
  },
  {
    slug: "ling-lingqi",
    name: "凌凌七",
    workSlug: "yi-qian-ling-yi-ye",
    workTitle: "一千零一夜",
    year: 2018,
    image: W["yi-qian-ling-yi-ye"],
    quote: "做梦是甜的，醒来也要继续甜。",
    description: "古灵精怪的花艺设计师，甜宠都市剧经典女主之一。",
  },
  {
    slug: "nie-jiuluo",
    name: "聂九罗",
    workSlug: "xiao-qi-qing-rang",
    workTitle: "枭起青壤",
    year: 2025,
    image: W["xiao-qi-qing-rang"],
    description: "神秘古域中的探险者，飒与媚并存，古装奇幻冒险新角色。",
  },
  {
    slug: "he-simu",
    name: "贺思慕",
    workSlug: "bai-ri-ti-deng",
    workTitle: "白日提灯",
    year: 2026,
    image: W["bai-ri-ti-deng"],
    description: "归墟万灵之主，活了四百年却保持少女模样，天生缺失五感，于人间与段胥以爱意抵抗时间洪流。",
    featured: true,
  },
  {
    slug: "jiang-li",
    name: "江离",
    workSlug: "ni-guang-zhi-lian",
    workTitle: "逆光之恋",
    year: 2015,
    image: W["ni-guang-zhi-lian"],
    description: "逃婚当天离奇身亡的富家女，以鬼魂身份在七日内追查真相，迪丽热巴早期网络剧女主。",
  },
  {
    slug: "guan-xiaodi",
    name: "关小迪",
    workSlug: "ma-la-bian-xing-ji",
    workTitle: "麻辣变形计",
    year: 2016,
    image: W["ma-la-bian-xing-ji"],
    description: "叛逆性感的女保镖，于魔鬼训练中成长为合格保镖，「火狼女」形象深入人心。",
  },
  {
    slug: "song-zihan",
    name: "宋子涵",
    workSlug: "ai-de-jie-ti",
    workTitle: "爱的阶梯",
    year: 2016,
    image: W["ai-de-jie-ti"],
    description: "宋天成之女，于家族恩怨与情感纠葛中演绎复杂人性。",
  },
  {
    slug: "su-yiqing",
    name: "苏溢青",
    workSlug: "liu-shan-men",
    workTitle: "六扇门",
    year: 2016,
    image: W["liu-shan-men"],
    description: "智勇双全的侠女，搭档林峯于武侠悬疑叙事中飒爽利落。",
  },
  {
    slug: "gong-sun-li",
    name: "公孙丽",
    workSlug: "qin-shi-liren-mingyue-xin",
    workTitle: "秦时丽人明月心",
    year: 2017,
    image: W["qin-shi-liren-mingyue-xin"],
    description: "乱世中的坚韧女性，于家国情仇间展现柔美与担当。",
  },
  {
    slug: "zhou-fang",
    name: "周放",
    workSlug: "xingfu-chushou-keji",
    workTitle: "幸福，触手可及！",
    year: 2020,
    image: W["xingfu-chushou-keji"],
    description: "独立干练的服装设计师，呈现都市女性在事业与爱情中的成长。",
  },
  {
    slug: "hao-meili",
    name: "郝美丽",
    workSlug: "peng-ran-xing-dong",
    workTitle: "怦然星动",
    year: 2015,
    image: W["peng-ran-xing-dong"],
    description: "早期大银幕客串，饰演耀眼明星一角。",
  },
  {
    slug: "tang-nannan",
    name: "唐楠楠",
    workSlug: "aojiao-yu-pianjian",
    workTitle: "傲娇与偏见",
    year: 2017,
    image: W["aojiao-yu-pianjian"],
    description: "元气满满的小说作家，首部主演院线爱情喜剧女主。",
  },
  {
    slug: "tong-tong",
    name: "彤彤",
    workSlug: "jie-you-zahuodian",
    workTitle: "解忧杂货店",
    year: 2017,
    image: W["jie-you-zahuodian"],
    description: "东野圭吾 IP 改编电影中的坏小子角色，一改以往女神形象。",
  },
  {
    slug: "liu-jiayin",
    name: "刘佳音",
    workSlug: "er-shi-yi-ke-la",
    workTitle: "21克拉",
    year: 2018,
    image: W["er-shi-yi-ke-la"],
    description: "节俭务实的都市女主，以轻喜剧探讨爱情与金钱观。",
  },
  {
    slug: "bai-fengjiu-zhen-shangshu",
    name: "白凤九",
    workSlug: "san-sheng-san-shi-zhen-shang-shu",
    workTitle: "三生三世枕上书",
    year: 2020,
    image: W["san-sheng-san-shi-zhen-shang-shu"],
    quote: "我是青丘白凤九，我要嫁的，是我的东华帝君。",
    description: "《枕上书》续篇女主，与高伟光（东华帝君）再续三生三世情缘；与《十里桃花》白凤九为同一角色不同篇章。",
    featured: true,
  },
  {
    slug: "wei-lan",
    name: "卫蓝",
    workSlug: "sui-ran-bu-neng-yiqie",
    workTitle: "虽然不能同时拥有一切",
    year: 2026,
    image: W["sui-ran-bu-neng-yiqie"],
    description:
      "一人分饰双生卫蓝——光鲜作家与隐忍主妇，于互换人生中完成自我觉醒，是迷你剧形态下的演技突破。",
    featured: true,
  },
  {
    slug: "jiu-chong-tian-unit",
    name: "待官宣",
    workSlug: "jiu-chong-tian",
    workTitle: "九重天",
    year: 2026,
    image: W["jiu-chong-tian"],
    description: "腾讯视频民国悬疑单元剧女主，2026 年进组拍摄；具体角色名以官方公布为准。",
  },
  {
    slug: "change",
    name: "嫦娥",
    workSlug: "ri-yue",
    workTitle: "日月",
    year: 2019,
    image: W["ri-yue"],
    description: "神话爱情电影待映角色，热爱自然、崇尚自由的新版嫦娥。",
  },
  {
    slug: "yu-long",
    name: "钰珑",
    nameEn: "Yu Long",
    workSlug: "shaolin-nvzu",
    workTitle: "功夫女足",
    workTitleEn: "Kung Fu Women's Soccer",
    year: 2026,
    image: W["shaolin-nvzu"],
    description:
      "峨眉队 8 号前锋、球队核心得分手；为贴合运动员形象增重 8 公斤并完成三个月封闭足球特训，路演中分享从零基础练到连续颠球 200 次。",
    descriptionEn:
      "Forward #8 and core scorer for Emei FC; gained 8 kg and trained three months — roadshow stories of 200 consecutive juggles from zero.",
    featured: true,
  },
  {
    slug: "ren-anle",
    name: "任安乐 / 帝梓元",
    workSlug: "an-le-zhuan",
    workTitle: "安乐传",
    year: 2023,
    image: W["an-le-zhuan"],
    description: "一人分饰两角，权谋与江湖之间演绎复仇、成长与家国情怀。",
  },
];
