import type { Honor, TimelineEntry } from "@/lib/types";

/**
 * 荣誉与里程碑，均以公开报道为准，仅收录正面信息。
 */
export const honors: Honor[] = [
  {
    year: 2026,
    title: "《功夫女足》累计票房突破 10 亿（据公开报道）",
    titleEn: "Kung Fu Women's Soccer passes 1 billion yuan box office (public reports)",
    source: "公开媒体 / 票房平台报道",
    sourceEn: "Media / box-office platform reports",
  },
  {
    year: 2026,
    title: "《功夫女足》上映首日票房突破 2 亿，打破 7 项影史纪录",
    titleEn: "Kung Fu Women's Soccer opening day passes 200M yuan, 7 records broken",
    source: "灯塔专业版 / 公开报道",
    sourceEn: "Lighthouse / public reports",
  },
  {
    year: 2026,
    title: "《功夫女足》定档上映，为角色增重 8 公斤完成足球特训",
    titleEn: "Kung Fu Women's Soccer release — 8 kg gain and football training for role",
    source: "公开报道 / 片方宣发",
    sourceEn: "Public reports / official promotion",
  },
  {
    year: 2026,
    title: "Fakeme 首位全球品牌代言人官宣",
    titleEn: "Fakeme first global brand ambassador announced",
    source: "品牌官宣 / 媒体报道",
    sourceEn: "Official brand announcement / media reports",
  },
  {
    year: 2026,
    title: "与嘉行传媒合约到期，个人工作室独立运营",
    titleEn: "Jaywalk contract ended; independent studio operations",
    source: "公开媒体报道",
    sourceEn: "Media reports",
  },
  {
    year: 2026,
    title: "可逐全球品牌代言人官宣",
    titleEn: "KAZOO global brand ambassador announced",
    source: "品牌官宣 / 媒体报道",
    sourceEn: "Official brand announcement / media reports",
  },
  {
    year: 2026,
    title: "路虎卫士全驭代言人官宣",
    titleEn: "Land Rover Defender brand ambassador announced",
    source: "公开官宣 / 媒体报道",
    sourceEn: "Official announcement / media reports",
  },
  {
    year: 2026,
    title: "VOGUE 八月刊单人封面进入宣传期，达成五大女刊单人正刊全满贯（刊面以官方为准）",
    titleEn: "VOGUE August solo cover in promo — Big Five solo-cover grand slam (official release TBA)",
    source: "时尚媒体报道（发售以杂志官方为准）",
    sourceEn: "Fashion media reports (on-sale dates follow the magazine)",
  },
  {
    year: 2026,
    title: "德佑全球品牌代言人官宣，商业版图持续扩展",
    titleEn: "Deeyeo global brand ambassador announced",
    source: "公开官宣 / 媒体报道",
    sourceEn: "Official announcement / media reports",
  },
  {
    year: 2026,
    title: "中国影视之夜获 CMG 年度推荐电视剧女演员",
    titleEn: "CMG Recommended TV Actress at China Film & TV Night",
    source: "公开报道",
    sourceEn: "Public reports",
  },
  {
    year: 2026,
    title: "《九重天》进组，《虽然不能同时拥有一切》预告发布",
    titleEn: "Nine Heavens filming; You Can't Have Everything trailer",
    source: "公开报道",
    sourceEn: "Public reports",
  },
  {
    year: 2026,
    title: "幸运咖臻选咖啡全球代言人官宣",
    titleEn: "Lucky Coffee premium coffee global brand ambassador announced",
    source: "品牌官宣 / 媒体报道",
    sourceEn: "Official brand announcement / media reports",
  },
  {
    year: 2026,
    title: "《白日提灯》热播，《嘉人》六月生日刊封面释出",
    titleEn: "Love Under the Lantern airs; Marie Claire June birthday cover",
    source: "公开播出信息 / 时尚媒体报道",
    sourceEn: "Broadcast info / fashion media",
  },
  {
    year: 2026,
    title: "开年蝉联多本主流时尚女刊封面，时尚影响力持续走高",
    titleEn: "Multiple major fashion covers at year start",
    source: "公开报道",
    sourceEn: "Public reports",
  },
  {
    year: 2025,
    title: "《利剑·玫瑰》《枭起青壤》播出，现实与古装题材口碑兼收",
    titleEn: "Sword Rose and The Legend of Shen Li — realism and fantasy both praised",
    source: "公开播出信息",
    sourceEn: "Broadcast info",
  },
  {
    year: 2025,
    title: "《枭起青壤》播出，古装奇幻冒险再获关注",
    titleEn: "The Legend of Shen Li gains attention in fantasy adventure",
    source: "公开播出信息",
    sourceEn: "Broadcast info",
  },
  {
    year: 2024,
    title: "Dior 全球品牌大使身份持续深化，巴黎时装周亮相",
    titleEn: "Dior global ambassador role deepens; Paris Fashion Week appearances",
    source: "公开媒体报道",
    sourceEn: "Media reports",
  },
  {
    year: 2023,
    title: "《安乐传》播出，一人分饰帝梓元 / 任安乐",
    titleEn: "The Legend of Anle — dual roles Di Ziyuan and Ren Anle",
    source: "公开播出信息",
    sourceEn: "Broadcast info",
  },
  {
    year: 2022,
    title: "《与君初相识·恰似故人归》热播，纪云禾广受好评",
    titleEn: "The Blue Whisper — Ji Yunhe widely praised",
    source: "公开播出数据",
    sourceEn: "Viewership data",
  },
  {
    year: 2023,
    title: "《公诉》开启现实题材转型，获行业关注与正面评价",
    titleEn: "The Prosecution marks realism pivot with industry acclaim",
    source: "公开媒体报道",
    sourceEn: "Media reports",
  },
  {
    year: 2021,
    title: "《你是我的荣耀》《长歌行》热播，口碑与收视双高",
    titleEn: "You Are My Glory and The Long Ballad — ratings and praise",
    source: "公开播出数据",
    sourceEn: "Viewership data",
  },
  {
    year: 2020,
    title: "多次登上福布斯中国名人榜（Celebrity 100）",
    titleEn: "Forbes China Celebrity 100 multiple times",
    source: "福布斯中国",
    sourceEn: "Forbes China",
  },
  {
    year: 2018,
    title: "第 12 届中国金鹰电视艺术节「金鹰女神」",
    titleEn: "12th China Golden Eagle Festival Golden Eagle Goddess",
    source: "中国金鹰电视艺术节",
    sourceEn: "China Golden Eagle TV Art Festival",
  },
  {
    year: 2018,
    title: "第 29 届中国电视金鹰奖「最具人气女演员」（《三生三世十里桃花》）",
    titleEn: "29th China TV Golden Eagle Award — Most Popular Actress (Eternal Love)",
    source: "中国电视金鹰奖",
    sourceEn: "China TV Golden Eagle Awards",
  },
  {
    year: 2017,
    title: "《三生三世十里桃花》白凤九广受好评，人气大幅跃升",
    titleEn: "Eternal Love — Bai Fengjiu boosts popularity",
    source: "公开播出数据",
    sourceEn: "Viewership data",
  },
  {
    year: 2016,
    title: "《麻辣变形计》关小迪人气走高",
    titleEn: "Hot Girl — Guan Xiaodi gains fans",
    source: "公开播出数据",
    sourceEn: "Viewership data",
  },
  {
    year: 2015,
    title: "《克拉恋人》高雯出圈，获国剧盛典最受欢迎新人女演员",
    titleEn: "Diamond Lover — Gao Wen breakout; Most Popular New Actress at Guoju Awards",
    source: "国剧盛典",
    sourceEn: "Guoju Awards",
  },
  {
    year: 2013,
    title: "《阿娜尔罕》央视首播，正式以演员身份出道",
    titleEn: "Anarhan CCTV premiere — official acting debut",
    source: "公开播出信息",
    sourceEn: "Broadcast info",
  },
  {
    year: 2014,
    title: "《古剑奇谭》芙蕖亮相",
    titleEn: "Legend of the Ancient Sword — Fuqu debut",
    source: "公开媒体报道",
    sourceEn: "Media reports",
  },
  {
    year: 2014,
    title: "《微时代》吴安珀、早期网络剧积累",
    titleEn: "We Era — Wu Anpo; early web drama experience",
    source: "公开播出信息",
    sourceEn: "Broadcast info",
  },
  {
    year: 2015,
    title: "《逆光之恋》女主江离，网络剧女主尝试",
    titleEn: "Love Against the Light — web drama lead Jiang Li",
    source: "公开播出信息",
    sourceEn: "Broadcast info",
  },
];

export const timeline: TimelineEntry[] = [
  {
    year: 2013,
    title: "正式出道",
    titleEn: "Acting debut",
    description: "出演《阿娜尔罕》，以演员身份进入公众视野。",
    descriptionEn: "Anarhan brings her into the public eye as an actress.",
  },
  {
    year: 2014,
    title: "崭露头角",
    titleEn: "Rising visibility",
    description: "《古剑奇谭》芙蕖、《微时代》吴安珀等角色陆续亮相，开始被更多观众认识。",
    descriptionEn: "Fuqu in Legend of the Ancient Sword and Wu Anpo in We Era gain recognition.",
  },
  {
    year: 2015,
    title: "双线并进",
    titleEn: "Dual breakthrough",
    description: "《逆光之恋》担纲网络剧女主，《克拉恋人》高雯出圈，知名度快速上升。",
    descriptionEn: "Web drama lead Jiang Li and breakout Gao Wen in Diamond Lover.",
  },
  {
    year: 2017,
    title: "白凤九经典",
    titleEn: "Bai Fengjiu icon",
    description:
      "《三生三世十里桃花》成为现象级仙侠剧，白凤九让她跻身一线。",
    descriptionEn: "Eternal Love becomes a phenomenon — Bai Fengjiu elevates her to top tier.",
  },
  {
    year: 2018,
    title: "金鹰双喜",
    titleEn: "Golden Eagle double honor",
    description:
      "当选第 12 届金鹰节「金鹰女神」，并获金鹰奖「最具人气女演员」。",
    descriptionEn: "Golden Eagle Goddess and Most Popular Actress at the 29th Golden Eagle Awards.",
  },
  {
    year: 2020,
    title: "枕上书女主",
    titleEn: "The Pillow Book lead",
    description:
      "《三生三世枕上书》独挑大梁，白凤九专属故事线延续经典仙侠宇宙。",
    descriptionEn: "Eternal Love of Dream — Bai Fengjiu's dedicated storyline continues the xianxia universe.",
  },
  {
    year: 2021,
    title: "口碑收视双高",
    titleEn: "Ratings and acclaim",
    description:
      "《长歌行》《你是我的荣耀》相继热播，演技与人气双线收获。",
    descriptionEn: "The Long Ballad and You Are My Glory — performance and popularity both soar.",
  },
  {
    year: 2023,
    title: "牵手 Dior",
    titleEn: "Dior partnership",
    description: "2023 年 2 月官宣 Dior 品牌大使，12 月升任全球品牌大使，时尚版图与国际曝光持续扩展。",
    descriptionEn: "Dior brand ambassador Feb 2023, global ambassador Dec 2023 — fashion and international exposure expand.",
  },
  {
    year: 2023,
    title: "现实题材转型",
    titleEn: "Realism pivot",
    description: "《公诉》《安乐传》播出，展现驾驭多元题材的能力。",
    descriptionEn: "The Prosecution and The Legend of Anle showcase diverse genres.",
  },
  {
    year: 2025,
    title: "现实主义进阶",
    titleEn: "Realism advance",
    description:
      "《利剑·玫瑰》于央视黄金档播出，现实题材表演再获认可。",
    descriptionEn: "Sword Rose on CCTV prime time — realism performance gains recognition.",
  },
  {
    year: 2026,
    title: "独立运营新阶段",
    titleEn: "Independent operations",
    description:
      "与嘉行传媒 13 年合约到期后，个人工作室全面接管演艺事务；《功夫女足》暑期档热映，公开报道累计票房破 10 亿；VOGUE 八月刊单人封面进入宣传期，达成五大女刊单人正刊全满贯。",
    descriptionEn:
      "After 13 years with Jaywalk, her studio fully manages career affairs; Kung Fu Women's Soccer summer run with ~1B yuan box office per reports; VOGUE August solo cover in promo completes the Big Five solo-cover set.",
  },
];
