import type { NewsItem } from "@/lib/types";
import { OFFICIAL_CHANNELS } from "./official-channels";

/** 最新动态：以公开信息为准，按时间倒序维护 */
export const news: NewsItem[] = [
  {
    slug: "china-film-tv-night-2026",
    title: "中国影视之夜红毯 · 获 CMG 年度推荐女演员",
    titleEn: "China Film & TV Night · CMG Recommended TV Actress",
    date: "2026-06-15",
    category: "event",
    summary:
      "时隔 605 天重返公开红毯，Georges Hobeika 高定搭配 Mikimoto 珠宝亮相；凭《利剑·玫瑰》获 CMG 年度推荐电视剧女演员。",
    summaryEn:
      "First red carpet in 605 days in Georges Hobeika couture and Mikimoto jewels; CMG Recommended TV Actress for Sword Rose.",
    body:
      "2026 中国影视之夜于上海国际电影节期间在上海举办，为总台主办的行业活动。迪丽热巴身着 Georges Hobeika 2026 春夏玫红钉珠鱼尾礼服亮相红毯，并获 CMG 年度推荐电视剧女演员。",
    bodyEn:
      "The 2026 China Film & TV Night was held in Shanghai during the film festival. Dilraba appeared in a Georges Hobeika 2026 SS gown and received CMG Recommended TV Actress.",
    eventSlug: "china-film-tv-night-2026",
    externalUrl: "https://k.sina.com.cn/article_7096020439_1a6f4add706801rzeo.html",
    featured: true,
  },
  {
    slug: "macalline-june-2026",
    title: "六月行程 · 红星美凯龙品牌活动",
    titleEn: "June Schedule · Macalline Brand Event",
    date: "2026-06-01",
    category: "event",
    summary: "工作室发布六月行程，6 月 27 日将出席红星美凯龙品牌活动。",
    summaryEn:
      "Studio released the June schedule — a Macalline brand event is set for June 27.",
    eventSlug: "macalline-brand-2026",
    externalUrl: OFFICIAL_CHANNELS.weibo.studio.href,
    featured: true,
  },
  {
    slug: "sui-ran-bu-neng-yiqie-trailer-news",
    title: "《虽然不能同时拥有一切》首支预告发布",
    date: "2026-04-20",
    category: "work",
    summary:
      "爱奇艺微尘剧场迷你剧释出首支预告，迪丽热巴一人分饰双生卫蓝，搭档陈昊森，改编自《蓝，另一种蓝》。",
    body:
      "该剧共 6 集，每集约 45 分钟，由翁子光监制、吴辰珵执导，卢文莹与王一寓编剧。拍摄横跨北京与泉州，通过都市与小镇的双线对比呈现两个卫蓝的人生落差。播出信息以爱奇艺平台官宣为准。",
    workSlug: "sui-ran-bu-neng-yiqie",
    externalUrl: "https://movie.douban.com/subject/36707564/",
    featured: true,
  },
  {
    slug: "jiu-chong-tian-filming",
    title: "《九重天》进组拍摄",
    date: "2026-01-12",
    category: "work",
    summary:
      "进组腾讯视频民国悬疑单元剧《九重天》，拍摄民国单元戏份，搭档尹昉；九个独立单元串联，以闽西琉璃寨土楼为舞台。",
    workSlug: "jiu-chong-tian",
    externalUrl: "https://movie.douban.com/subject/37191662/",
    featured: true,
  },
  {
    slug: "jia-ren-june-2026",
    title: "《嘉人》六月刊生日封面",
    titleEn: "Marie Claire June Birthday Cover",
    date: "2026-06-02",
    category: "fashion",
    summary: "登上《嘉人》2026 年 6 月生日刊封面「AS SHE IS / 如她所是」，成为中国 90 后首位完成五大女刊全满贯的艺人。",
    summaryEn:
      "Covers Marie Claire China June 2026 \"AS SHE IS\" — first post-90s artist to complete China's \"Big Five\" women's magazine cover grand slam.",
    magazineSlug: "jia-ren-2026-06",
    externalUrl: "https://www.marieclaire.com.cn/",
    featured: true,
  },
  {
    slug: "birthday-2026",
    title: "2026 生日 · 六月行程发布",
    titleEn: "2026 Birthday · June Schedule",
    date: "2026-06-03",
    category: "event",
    summary: "工作室发布 6 月 3 日生日祝福与六月行程，开启「甜心模式」夏日奇遇。",
    summaryEn:
      "Studio shared birthday wishes on June 3 and released the June schedule — \"sweetheart mode\" summer adventures.",
    eventSlug: "birthday-2026",
    externalUrl: OFFICIAL_CHANNELS.weibo.studio.href,
    featured: true,
  },
  {
    slug: "bai-ri-ti-deng-air",
    title: "《白日提灯》腾讯视频开播",
    date: "2026-03-28",
    category: "work",
    summary: "古装奇幻爱情剧（原名《慕胥辞》）于腾讯视频独播，饰演归墟鬼王贺思慕，搭档陈飞宇。",
    workSlug: "bai-ri-ti-deng",
    externalUrl: "https://movie.douban.com/subject/35929169/",
    featured: true,
  },
  {
    slug: "elle-2026-cover",
    title: "ELLE 2026 开季刊封面发布",
    date: "2026-02-20",
    category: "fashion",
    summary: "登上 ELLE 世界时装之苑 2026 年 3 月开季刊封面，主题「万变之中」。",
    magazineSlug: "elle-2026-03",
    externalUrl: "https://www.elle.com.cn/",
    featured: true,
  },
  {
    slug: "dior-suzhou-2026",
    title: "Dior 苏州高级珠宝活动",
    date: "2026-03-20",
    category: "fashion",
    summary: "以 Dior 全球品牌大使身份出席苏州高级珠宝晚宴，佩戴 Belle Dior 系列珠宝亮相。",
    eventSlug: "dior-suzhou-high-jewelry-2026",
    externalUrl: "https://news.qq.com/rain/a/20260320A08FSQ00",
    featured: true,
  },
  {
    slug: "li-jian-mei-gui-air",
    title: "《利剑·玫瑰》央视黄金档热播",
    date: "2025-07-28",
    category: "work",
    summary: "现实打拐题材剧于央视八套黄金档播出，饰演一线女警邓妍。",
    workSlug: "li-jian-mei-gui",
    externalUrl: "https://movie.douban.com/subject/35597542/",
    featured: true,
  },
  {
    slug: "xiao-qi-qing-rang-air",
    title: "《枭起青壤》正式播出",
    date: "2025-11-22",
    category: "work",
    summary: "古装奇幻冒险剧于腾讯视频上线，搭档陈星旭出演聂九罗。",
    workSlug: "xiao-qi-qing-rang",
    externalUrl: "https://movie.douban.com/subject/35489172/",
    featured: true,
  },
  {
    slug: "bazaar-2025-cover",
    title: "时尚芭莎九月刊封面",
    date: "2025-08-15",
    category: "fashion",
    summary: "2025 年 9 月号封面大片「大冒险家 Limitless」。",
    magazineSlug: "bazaar-2025-09",
    externalUrl: "https://www.harpersbazaar.com.cn/",
  },
  {
    slug: "dior-paris-2024",
    title: "Dior 巴黎时装周",
    date: "2024-02-27",
    category: "event",
    summary: "受邀出席巴黎时装周 Dior 大秀，亮相国际时尚舞台。",
    eventSlug: "dior-paris-fashion-week-2024",
    externalUrl: "https://www.dior.com/en_int/womens-fashion/shows",
  },
  {
    slug: "gong-su-premiere",
    title: "《公诉》开播",
    date: "2023-05-29",
    category: "work",
    summary: "现实题材法治剧开播，饰演检察官安旎，开启现实主义转型之路。",
    workSlug: "gong-su",
    externalUrl: "https://movie.douban.com/subject/35525475/",
  },
  {
    slug: "henan-relief-2021",
    title: "驰援河南暴雨灾区",
    date: "2021-07-22",
    category: "charity",
    summary: "河南特大暴雨期间个人捐款驰援，并呼吁粉丝理性关注、共同支援抗灾。",
    externalUrl: OFFICIAL_CHANNELS.weibo.studio.href,
  },
];
