import type { VideoItem } from "@/lib/types";
import { IMAGES } from "./images";
import { OFFICIAL_CHANNELS } from "./official-channels";

const w = IMAGES.works;
const p = IMAGES.portraits;
const m = IMAGES.magazines;
const ev = IMAGES.events;

/**
 * 视频专区：链接均为公开平台播放页，本站不托管视频文件。
 */
export const videos: VideoItem[] = [
  {
    slug: "gongfu-nvzu-boxoffice-17yi-2026-video",
    title: "《功夫女足》累计票房破 17 亿 · 续集确认",
    titleEn: "Kung Fu Women's Soccer · 1.7B+ & Sequel",
    date: "2026-07-23",
    category: "event",
    platform: "other",
    href: "https://ent.sina.cn/2026-07-24/detail-iniivtws4422361.d.html",
    thumbnail: w["shaolin-nvzu"],
    summary: "据公开报道累计票房破 17 亿；周星驰路演确认将拍续集。",
    summaryEn: "Public reports: 1.7B+ box office; sequel confirmed on the roadshow.",
    workSlug: "shaolin-nvzu",
    featured: true,
  },
  {
    slug: "gongfu-nvzu-boxoffice-14yi-2026-video",
    title: "《功夫女足》累计票房超 14.57 亿",
    titleEn: "Kung Fu Women's Soccer · 1.457B+ Box Office",
    date: "2026-07-19",
    category: "event",
    platform: "other",
    href: "https://ent.sina.cn/2026-07-20/detail-iniiktnw4921485.d.html",
    thumbnail: w["shaolin-nvzu"],
    summary: "据公开报道，截至 7 月 19 日累计票房超 14.57 亿；个人主演电影票房破 20 亿。",
    summaryEn: "Public reports: 1.457B+ by July 19; starring filmography crosses 2B yuan.",
    workSlug: "shaolin-nvzu",
    featured: false,
  },
  {
    slug: "be-water-selfie-2026-video",
    title: "「Be water」素颜自拍 · 工作室动态",
    titleEn: "“Be water” Bare-faced Selfies",
    date: "2026-07-18",
    category: "studio",
    platform: "weibo",
    href: "https://ent.sina.cn/2026-07-18/detail-iniifhuc8372432.d.html",
    thumbnail: w["shaolin-nvzu"],
    summary: "微博原相机素颜自拍，配文「Be water, my friend~」，回应增重传言并为《功夫女足》造势。",
    summaryEn: "Unfiltered Weibo selfies captioned “Be water, my friend~” — candid reply while promoting the film.",
    workSlug: "shaolin-nvzu",
    featured: true,
  },
  {
    slug: "gongfu-nvzu-boxoffice-10yi-2026-video",
    title: "《功夫女足》累计票房破 10 亿",
    titleEn: "Kung Fu Women's Soccer · 1B+ Box Office",
    date: "2026-07-17",
    category: "event",
    platform: "other",
    href: "https://www.toutiao.com/article/7663411019796824610/",
    thumbnail: w["shaolin-nvzu"],
    summary: "据公开报道，上映约一周累计综合票房突破 10 亿元；数据以专业平台为准。",
    summaryEn: "Public reports: ~1B yuan cumulative about a week after release — follow live platform data.",
    workSlug: "shaolin-nvzu",
    featured: true,
  },
  {
    slug: "gongfu-nvzu-tianjin-roadshow-2026-video",
    title: "《功夫女足》天津路演 · 现场回顾",
    titleEn: "Kung Fu Women's Soccer · Tianjin Roadshow Highlights",
    date: "2026-07-11",
    category: "event",
    platform: "weibo",
    href: "https://ent.sina.cn/2026-07-12/detail-inihnnkp8101688.d.html",
    thumbnail: w["shaolin-nvzu"],
    summary: "上映首日天津路演，工作室发布 Live 图，分享角色特训经历。",
    summaryEn: "Opening-day Tianjin roadshow — studio live photos and training stories.",
    workSlug: "shaolin-nvzu",
    featured: true,
  },
  {
    slug: "gongfu-nvzu-boxoffice-day1-2026-video",
    title: "《功夫女足》上映首日票房破 2 亿",
    titleEn: "Kung Fu Women's Soccer · 200M+ Opening Day",
    date: "2026-07-11",
    category: "event",
    platform: "other",
    href: "https://ent.sina.cn/2026-07-12/detail-inihpchf8004605.d.html",
    thumbnail: w["shaolin-nvzu"],
    summary: "据灯塔专业版，首日票房突破 2 亿元，打破 7 项中国影史纪录。",
    summaryEn: "Lighthouse reports 200M+ opening day, 7 box-office records broken.",
    workSlug: "shaolin-nvzu",
    featured: true,
  },
  {
    slug: "gongfu-nvzu-long-trailer-2026-video",
    title: "《功夫女足》首支长预告",
    titleEn: "Kung Fu Women's Soccer · Full Trailer",
    date: "2026-07-10",
    category: "trailer",
    platform: "other",
    href: "https://ent.sina.cn/2026-07-10/detail-inihinfz5203133.d.html",
    thumbnail: w["shaolin-nvzu"],
    summary: "7 月 10 日发布首支完整长预告，定档 7 月 11 日全国上映。",
    summaryEn: "Full trailer released July 10 — opens July 11 nationwide.",
    workSlug: "shaolin-nvzu",
    featured: true,
  },
  {
    slug: "gongfu-nvzu-dingdang-2026-video",
    title: "《功夫女足》定档预告",
    titleEn: "Kung Fu Women's Soccer · Release Trailer",
    date: "2026-07-06",
    category: "trailer",
    platform: "other",
    href: "https://ent.sina.cn/2026-07-06/detail-inifwfpx1891264.d.html",
    thumbnail: w["shaolin-nvzu"],
    summary: "7 月 6 日片方发布定档海报与预告，确认 7 月 11 日全国上映。",
    summaryEn: "Release trailer and poster dropped July 6 — opens July 11 nationwide.",
    workSlug: "shaolin-nvzu",
    featured: true,
  },
  {
    slug: "ambrosial-xian-2026-video",
    title: "安慕希西安品牌活动 · 现场回顾",
    titleEn: "Ambrosial Xi'an Event · On-Site Highlights",
    date: "2026-07-05",
    category: "event",
    platform: "weibo",
    href: "https://www.sina.cn/news/detail/5316700406809642.html",
    thumbnail: p.tealFloral,
    summary: "西安夏日冰雪城品牌活动，AADNEVIK 冰蓝色高定裙装亮相。",
    summaryEn: "Summer Ice City event in Xi'an — AADNEVIK ice-blue couture.",
    featured: true,
  },
  {
    slug: "fakeme-live-2026-video",
    title: "Fakeme 梦镜商店 · 直播回顾",
    titleEn: "Fakeme Dream Mirror Store · Live Highlights",
    date: "2026-04-13",
    category: "event",
    platform: "other",
    href: "https://www.sina.cn/news/detail/5287341950507321.html",
    thumbnail: p.goldCrown,
    summary: "4 月 13 日 Fakeme 抖音品牌直播，高定造型与墨镜产品线互动。",
    summaryEn: "April 13 Fakeme Douyin live — couture looks and eyewear showcase.",
    featured: true,
  },
  {
    slug: "land-rover-urban-camp-2026-video",
    title: "路虎卫士都市营地 · 上海活动现场",
    titleEn: "Land Rover Defender Urban Camp · Shanghai Highlights",
    date: "2026-07-03",
    category: "event",
    platform: "weibo",
    href: "https://www.sina.cn/news/detail/5316277541014141.html",
    thumbnail: ev.landRoverUrbanCamp2026,
    summary: "7 月 3 日出席上海都市营地，Julien Fournié 定制高定亮相。",
    summaryEn: "July 3 Urban Camp in Shanghai — Julien Fournié custom couture.",
    featured: true,
  },
  {
    slug: "land-rover-defender-2026-video",
    title: "路虎卫士全驭代言人官宣",
    titleEn: "Land Rover Defender Ambassador Announcement",
    date: "2026-06-20",
    category: "event",
    platform: "weibo",
    href: "https://www.sina.cn/news/detail/5311824748614498.html",
    thumbnail: ev.landRoverDefender2026,
    summary: "6 月 20 日正式官宣路虎卫士全驭代言人。",
    summaryEn: "Official Land Rover Defender brand ambassador announcement on June 20.",
    featured: true,
  },
  {
    slug: "macalline-shenyang-2026-video",
    title: "红星美凯龙沈阳品牌活动 · 现场回顾",
    titleEn: "Macalline Shenyang Event · On-Site Highlights",
    date: "2026-06-28",
    category: "event",
    platform: "weibo",
    href: "https://ent.sina.cn/2026-06-28/detail-inieykzq0408857.d.html",
    thumbnail: ev.macallineShenyang2026,
    summary: "沈阳线下品牌活动，粉丝合唱《追光者》互动名场面。",
    summaryEn: 'Shenyang brand event — fans sang "Chaser of Light" in a widely shared moment.',
    featured: true,
  },
  {
    slug: "deeyeo-global-2026",
    title: "德佑全球品牌代言人官宣",
    titleEn: "Deeyeo Global Ambassador Announcement",
    date: "2026-06-13",
    category: "event",
    platform: "weibo",
    href: "https://k.sina.com.cn/article_7857201856_1d45362c001906pez6.html",
    thumbnail: ev.deeyeoGlobal2026,
    summary: "6 月 13 日正式官宣德佑全球品牌代言人。",
    summaryEn: "Official Deeyeo global ambassador announcement on June 13.",
    featured: true,
  },
  {
    slug: "lucky-coffee-global-2026-video",
    title: "幸运咖臻选咖啡全球代言人官宣",
    titleEn: "Lucky Coffee Global Ambassador Announcement",
    date: "2026-04-19",
    category: "event",
    platform: "other",
    href: "https://news.qq.com/rain/a/20260420A04R8Y00",
    thumbnail: ev.luckyCoffeeGlobal2026,
    summary: "4 月 19 日正式官宣臻选咖啡全球代言人，品牌 TVC「相信就幸运」同步上线。",
    summaryEn: 'Official premium coffee global ambassador announcement April 19 — "Believe in Luck" TVC.',
    featured: true,
  },
  {
    slug: "jia-ren-cover-2026-video",
    title: "《嘉人》六月刊 · 生日封面预告",
    titleEn: "Marie Claire June Cover Teaser",
    date: "2026-06-02",
    category: "studio",
    platform: "weibo",
    href: "https://www.marieclaire.com.cn/",
    thumbnail: m.jiaren2026,
    summary: "「AS SHE IS / 如她所是」生日刊封面发布。",
    summaryEn: '"AS SHE IS" birthday cover release.',
    featured: true,
  },
  {
    slug: "china-film-tv-night-2026",
    title: "2026 中国影视之夜 · 红毯回顾",
    titleEn: "2026 China Film & TV Night · Red Carpet",
    date: "2026-06-15",
    category: "event",
    platform: "weibo",
    href: "https://weibo.com/search?q=中国影视之夜%20迪丽热巴",
    thumbnail: ev.chinaFilmTvNight2026,
    summary: "Georges Hobeika 高定搭配 Mikimoto 珠宝，时隔 605 天重返红毯。",
    summaryEn: "Georges Hobeika couture with Mikimoto jewels — red carpet return after 605 days.",
    featured: true,
  },
  {
    slug: "sui-ran-shuangsheng-trailer",
    title: "《虽然不能同时拥有一切》双生交汇版预告",
    titleEn: "You Can't Have Everything — Twin Wei Lan Trailer",
    date: "2026-04-20",
    category: "trailer",
    platform: "other",
    href: "https://www.iqiyi.com/v_232u2nily44.html",
    thumbnail: w["sui-ran-bu-neng-yiqie"],
    summary: "爱奇艺微尘剧场 · 一人分饰双生卫蓝。",
    summaryEn: "iQiyi Micro Drama — Dilraba as twin Wei Lans.",
    workSlug: "sui-ran-bu-neng-yiqie",
    featured: true,
  },
  {
    slug: "zhen-shang-shu-trailer",
    title: "《三生三世枕上书》预告 · 白凤九",
    date: "2020-01-25",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=三生三世枕上书",
    thumbnail: w["san-sheng-san-shi-zhen-shang-shu"],
    workSlug: "san-sheng-san-shi-zhen-shang-shu",
    featured: true,
  },
  {
    slug: "sui-ran-bu-neng-yiqie-trailer",
    title: "《虽然不能同时拥有一切》首支预告",
    date: "2026-04-20",
    category: "trailer",
    platform: "other",
    href: "https://www.iqiyi.com/search/虽然不能同时拥有一切.html",
    thumbnail: w["sui-ran-bu-neng-yiqie"],
    summary: "双生卫蓝互换人生，爱奇艺微尘剧场待播。",
    workSlug: "sui-ran-bu-neng-yiqie",
    featured: true,
  },
  {
    slug: "shili-taohua-trailer",
    title: "《三生三世十里桃花》预告 · 白凤九",
    date: "2017-01-30",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=三生三世十里桃花",
    thumbnail: w["sannshengsanshi-shili-taohua"],
    workSlug: "sannshengsanshi-shili-taohua",
    featured: true,
  },
  {
    slug: "ke-la-lian-ren-trailer",
    title: "《克拉恋人》预告 · 高雯",
    date: "2015-07-07",
    category: "trailer",
    platform: "other",
    href: "https://www.iqiyi.com/search/克拉恋人.html",
    thumbnail: w["ke-la-lian-ren"],
    workSlug: "ke-la-lian-ren",
  },
  {
    slug: "lie-huo-ru-ge-trailer",
    title: "《烈火如歌》预告 · 烈如歌",
    date: "2018-03-01",
    category: "trailer",
    platform: "youku",
    href: "https://so.youku.com/search_video/q_烈火如歌",
    thumbnail: w["lie-huo-ru-ge"],
    workSlug: "lie-huo-ru-ge",
  },
  {
    slug: "yu-jiao-ji-trailer",
    title: "《与君初相识》预告 · 纪云禾",
    date: "2022-03-17",
    category: "trailer",
    platform: "youku",
    href: "https://so.youku.com/search_video/q_与君初相识",
    thumbnail: w["yu-jiao-ji"],
    workSlug: "yu-jiao-ji",
  },
  {
    slug: "xingfu-trailer",
    title: "《幸福，触手可及！》预告 · 周放",
    date: "2020-05-18",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=幸福触手可及",
    thumbnail: w["xingfu-chushou-keji"],
    workSlug: "xingfu-chushou-keji",
  },
  {
    slug: "pao-pao-variety",
    title: "《奔跑吧》名场面",
    date: "2020-05-22",
    category: "variety",
    platform: "bilibili",
    href: "https://search.bilibili.com/all?keyword=奔跑吧+迪丽热巴",
    thumbnail: w["pao-pao"],
    workSlug: "pao-pao",
  },
  {
    slug: "jixian-variety",
    title: "《极限挑战》第五季片段",
    date: "2019-05-12",
    category: "variety",
    platform: "bilibili",
    href: "https://search.bilibili.com/all?keyword=极限挑战+迪丽热巴",
    thumbnail: w["ji-xian-tiao-zhan"],
    workSlug: "ji-xian-tiao-zhan",
  },
  {
    slug: "kaishi-s2-variety",
    title: "《开始推理吧》第二季",
    date: "2024-05-01",
    category: "variety",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=开始推理吧+第二季",
    thumbnail: w["kaishi-tuili-ba-s2"],
    workSlug: "kaishi-tuili-ba-s2",
  },
  {
    slug: "jiu-chong-tian-trailer",
    title: "《九重天》官宣物料",
    date: "2026-01-01",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=九重天+迪丽热巴",
    thumbnail: w["jiu-chong-tian"],
    summary: "腾讯视频 S+ 民国悬疑单元剧，2026 年拍摄中。",
    workSlug: "jiu-chong-tian",
  },
  {
    slug: "ri-yue-trailer",
    title: "《日月》先导预告",
    date: "2019-06-01",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=日月+迪丽热巴",
    thumbnail: w["ri-yue"],
    summary: "神话爱情电影，搭档窦骁饰演嫦娥。",
    workSlug: "ri-yue",
  },
  {
    slug: "shaolin-nvzu-trailer",
    title: "《少林女足》官宣",
    date: "2025-01-01",
    category: "trailer",
    platform: "other",
    href: "https://movie.douban.com/subject/36452545/",
    thumbnail: w["shaolin-nvzu"],
    summary: "周星驰导演待映电影。",
    workSlug: "shaolin-nvzu",
  },
  {
    slug: "wei-shi-dai-trailer",
    title: "《微时代》片段 · 吴安珀",
    date: "2014-07-21",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=微时代",
    thumbnail: w["wei-shi-dai"],
    summary: "腾讯自制青春网络剧，饰演博翰大学校花吴安珀。",
    workSlug: "wei-shi-dai",
  },
  {
    slug: "kaishi-tuili-ba-s3-highlight",
    title: "《开始推理吧 第三季》名场面",
    date: "2025-06-01",
    category: "variety",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=开始推理吧+第三季",
    thumbnail: w["kaishi-tuili-ba-s3"],
    summary: "2025 年剧情推理真人秀第三季常驻嘉宾。",
    workSlug: "kaishi-tuili-ba-s3",
    featured: true,
  },
  {
    slug: "huaer-silu-highlight",
    title: "《花儿与少年·丝路季》民族舞片段",
    date: "2023-12-05",
    category: "variety",
    platform: "other",
    href: "https://so.mgtv.com/so?k=花儿与少年+丝路季+迪丽热巴",
    thumbnail: w["huaer-yu-shaonian-silu"],
    summary: "船上展示维吾尔族舞蹈，获外交部发言人转发点赞。",
    workSlug: "huaer-yu-shaonian-silu",
    featured: true,
  },
  {
    slug: "ni-guang-zhi-lian-trailer",
    title: "《逆光之恋》预告 · 江离",
    date: "2015-02-02",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=逆光之恋",
    thumbnail: w["ni-guang-zhi-lian"],
    summary: "校园魔幻网络剧，饰演女主江离。",
    workSlug: "ni-guang-zhi-lian",
  },
  {
    slug: "chuangzaoying-2019-highlight",
    title: "《创造营 2019》发起人舞台",
    date: "2019-04-06",
    category: "variety",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=创造营2019",
    thumbnail: w["chuangzaoying-2019"],
    summary: "担任男团成长综艺发起人（班主任）。",
    workSlug: "chuangzaoying-2019",
  },
  {
    slug: "bai-ri-ti-deng-trailer",
    title: "《白日提灯》预告 · 贺思慕",
    date: "2026-02-14",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=白日提灯",
    thumbnail: w["bai-ri-ti-deng"],
    duration: "预告",
    summary: "古装奇幻爱情，饰演归墟鬼王贺思慕，腾讯视频独播。",
    workSlug: "bai-ri-ti-deng",
    featured: true,
  },
  {
    slug: "li-jian-mei-gui-trailer",
    title: "《利剑·玫瑰》预告 · 邓妍",
    date: "2025-06-01",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?q=利剑玫瑰",
    thumbnail: w["li-jian-mei-gui"],
    duration: "预告",
    summary: "现实打拐题材，央视八套黄金档播出。",
    workSlug: "li-jian-mei-gui",
    featured: true,
  },
  {
    slug: "xiao-qi-qing-rang-trailer",
    title: "《枭起青壤》预告 · 聂九罗",
    date: "2025-05-15",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?query=枭起青壤",
    thumbnail: w["xiao-qi-qing-rang"],
    duration: "预告",
    summary: "古装奇幻冒险，搭档陈星旭，腾讯视频播出。",
    workSlug: "xiao-qi-qing-rang",
    featured: true,
  },
  {
    slug: "ni-shi-wo-de-rongyao-trailer",
    title: "《你是我的荣耀》官方预告",
    date: "2021-07-01",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?q=你是我的荣耀",
    thumbnail: w["ni-shi-wo-de-rongyao"],
    duration: "预告",
    workSlug: "ni-shi-wo-de-rongyao",
    featured: true,
  },
  {
    slug: "chang-ge-xing-trailer",
    title: "《长歌行》预告 · 李长歌",
    date: "2021-03-20",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?q=长歌行",
    thumbnail: w["chang-ge-xing"],
    workSlug: "chang-ge-xing",
  },
  {
    slug: "gong-su-trailer",
    title: "《公诉》宣传特辑",
    date: "2023-05-10",
    category: "trailer",
    platform: "tencent",
    href: "https://v.qq.com/x/search/?q=公诉",
    thumbnail: w["gong-su"],
    workSlug: "gong-su",
  },
  {
    slug: "an-le-zhuan-trailer",
    title: "《安乐传》预告",
    date: "2023-07-01",
    category: "trailer",
    platform: "youku",
    href: "https://www.youku.com/ku/websearch?keyword=安乐传",
    thumbnail: w["an-le-zhuan"],
    workSlug: "an-le-zhuan",
  },
  {
    slug: "studio-birthday-2026",
    title: "迪丽热巴工作室 · 2026 生日祝福",
    date: "2026-06-03",
    category: "studio",
    platform: "weibo",
    href: OFFICIAL_CHANNELS.weibo.studio.href,
    thumbnail: m.grazia2026,
    summary: "工作室发布生日祝福与六月行程。",
    featured: true,
  },
  {
    slug: "studio-birthday-2025",
    title: "迪丽热巴工作室 · 生日祝福",
    date: "2025-06-03",
    category: "studio",
    platform: "weibo",
    href: OFFICIAL_CHANNELS.weibo.studio.href,
    thumbnail: m.elle2023,
    summary: "工作室官方微博发布的生日相关视频与图文。",
    featured: true,
  },
  {
    slug: "studio-li-jian-premiere",
    title: "工作室 ·《利剑·玫瑰》开播",
    date: "2025-07-28",
    category: "studio",
    platform: "weibo",
    href: OFFICIAL_CHANNELS.weibo.studio.href,
    thumbnail: w["li-jian-mei-gui"],
    summary: "央视黄金档开播宣传。",
  },
  {
    slug: "dior-suzhou-event",
    title: "Dior 苏州高级珠宝活动",
    date: "2026-03-20",
    category: "event",
    platform: "weibo",
    href: "https://news.qq.com/rain/a/20260320A08FSQ00",
    thumbnail: ev.diorSuzhou2026,
    summary: "全球品牌大使出席苏州高级珠宝晚宴，佩戴 Belle Dior 系列珠宝亮相。",
    featured: true,
  },
  {
    slug: "sweet-dreams-mv",
    title: "《一千零一夜》插曲 MV",
    date: "2018-06-15",
    category: "mv",
    platform: "bilibili",
    href: "https://search.bilibili.com/all?keyword=一千零一夜+迪丽热巴",
    thumbnail: w["yi-qian-ling-yi-ye"],
    workSlug: "yi-qian-ling-yi-ye",
  },
  {
    slug: "golden-eagle-interview",
    title: "金鹰节相关采访片段",
    date: "2018-10-14",
    category: "interview",
    platform: "bilibili",
    href: "https://search.bilibili.com/all?keyword=迪丽热巴+金鹰",
    thumbnail: p.goldCrown,
    summary: "2018 金鹰女神相关公开报道与采访。",
  },
  {
    slug: "variety-happy-camp",
    title: "综艺名场面合集",
    date: "2017-01-01",
    category: "variety",
    platform: "bilibili",
    href: "https://search.bilibili.com/all?keyword=迪丽热巴+综艺",
    thumbnail: p.tealFloral,
    summary: "快乐大本营等综艺公开片段检索。",
  },
];
