import type { Work } from "@/lib/types";
import { IMAGES } from "./images";

const w = IMAGES.works;

/**
 * 完整影视年表（电视剧 / 电影 / 综艺），以维基百科及公开报道为准。
 * 仅收录正面、公开的作品信息；海报均为本地托管、逐张核对的真实海报。
 */
export const works: Work[] = [
  // ===== 电视剧 =====
  {
    slug: "ana-er-han",
    title: "阿娜尔罕",
    titleEn: "Anarhan",
    type: "tv",
    year: 2013,
    role: "阿娜尔罕",
    poster: w["ana-er-han"],
    synopsis:
      "近代革命题材剧，迪丽热巴出道首部电视剧并担任女主角，饰演南疆姑娘阿娜尔罕，在解放军帮助下反抗旧恶势力、追求幸福，展现民族风情与坚韧品格。",
    highlights: ["出道首部电视剧", "央视一套首播"],
    status: "released",
    airInfo: "央视一套 · 2013 年 5 月播出",
  },
  {
    slug: "gu-jian-qi-tan",
    title: "古剑奇谭",
    titleEn: "Swords of Legends",
    type: "tv",
    year: 2014,
    role: "芙蕖",
    poster: w["gu-jian-qi-tan"],
    synopsis:
      "改编自同名仙侠游戏，迪丽热巴出演天墉城弟子芙蕖，温柔善良、灵气初显，是其早期古装剧作品之一。",
    highlights: ["早期仙侠题材", "芙蕖一角温柔灵动"],
    status: "released",
  },
  {
    slug: "wei-shi-dai",
    title: "微时代",
    titleEn: "V Love",
    type: "tv",
    year: 2014,
    role: "吴安珀",
    poster: w["wei-shi-dai"],
    synopsis:
      "腾讯自制都市青春网络剧（又名《微时代之恋·初恋篇》），迪丽热巴饰演博翰大学校花吴安珀，与高伟光、张云龙、李溪芮等合作，以新媒体时代的爱情与成长为主线。",
    highlights: ["杨幂工作室时期作品", "吴安珀一角"],
    status: "released",
    airInfo: "腾讯视频 · 2014 年 7 月 21 日起播",
  },
  {
    slug: "feng-zhong-qiyuan",
    title: "风中奇缘",
    titleEn: "Sound of the Desert",
    type: "tv",
    year: 2014,
    role: "骊姬",
    poster: w["feng-zhong-qiyuan"],
    synopsis:
      "改编自桐华小说《大漠谣》的古装传奇剧，迪丽热巴客串饰演西域女子骊姬，于胡歌、刘诗诗、彭于晏等主演的史诗叙事中亮相。",
    highlights: ["早期古装客串", "骊姬一角"],
    status: "released",
    airInfo: "湖南卫视 · 2014 年 10 月 1 日起播",
  },
  {
    slug: "mei-ren-zhi-zao",
    title: "美人制造",
    titleEn: "Cosmetology High",
    type: "tv",
    year: 2014,
    role: "倾城",
    poster: w["mei-ren-zhi-zao"],
    synopsis:
      "古装周播剧，迪丽热巴特邀出演李旦爱妃「倾城」，唐装造型惊艳亮相，是其早期古装客串代表作之一。",
    highlights: ["唐装造型", "特邀出演"],
    status: "released",
  },
  {
    slug: "ke-la-lian-ren",
    title: "克拉恋人",
    titleEn: "Diamond Lover",
    type: "tv",
    year: 2015,
    role: "高雯",
    poster: w["ke-la-lian-ren"],
    synopsis:
      "都市爱情剧，迪丽热巴饰演明艳张扬的珠宝设计师高雯，与唐嫣、Rain 等合作，进一步打开知名度。",
    highlights: ["都市时尚题材", "高雯一角讨喜出圈"],
    status: "released",
  },
  {
    slug: "ban-shu-chuan-qi",
    title: "班淑传奇",
    titleEn: "Ban Shu Legend",
    type: "tv",
    year: 2015,
    role: "安心",
    poster: w["ban-shu-chuan-qi"],
    synopsis:
      "古装励志传奇剧，迪丽热巴特别出演楼兰王女「安心」，于宫学比试等情节中展现异域风情与灵动气质。",
    highlights: ["特别出演", "楼兰公主安心"],
    status: "released",
  },
  {
    slug: "ni-guang-zhi-lian",
    title: "逆光之恋",
    titleEn: "The Backlight of Love",
    type: "tv",
    year: 2015,
    role: "江离",
    poster: w["ni-guang-zhi-lian"],
    synopsis:
      "都市校园奇幻网络剧，迪丽热巴担任女主角，饰演逃婚当天离奇身亡、以鬼魂身份调查真相的富家女江离。",
    highlights: ["网络剧女主", "魔幻悬疑题材"],
    status: "released",
    airInfo: "腾讯视频 · 2015 年 2 月播出",
  },
  {
    slug: "ma-la-bian-xing-ji",
    title: "麻辣变形计",
    titleEn: "Hot Girl",
    type: "tv",
    year: 2016,
    role: "关小迪",
    poster: w["ma-la-bian-xing-ji"],
    synopsis:
      "都市热血励志剧，迪丽热巴饰演叛逆性感的女保镖关小迪，于残酷训练中成长为合格保镖，展现「女汉子」魅力。",
    highlights: ["都市热血女主", "关小迪一角人气走高"],
    status: "released",
    airInfo: "湖南卫视 · 2016 年 8 月播出",
  },
  {
    slug: "liu-shan-men",
    title: "六扇门",
    titleEn: "Six Doors",
    type: "tv",
    year: 2016,
    role: "苏溢青",
    poster: w["liu-shan-men"],
    synopsis:
      "古装武侠悬疑剧，迪丽热巴搭档林峯，饰演侠女苏溢青，智勇双全、飒爽利落。",
    highlights: ["古装侠女", "搭档林峯"],
    status: "released",
  },
  {
    slug: "ai-de-jie-ti",
    title: "爱的阶梯",
    titleEn: "The Ladder of Love",
    type: "tv",
    year: 2016,
    role: "宋子涵",
    poster: w["ai-de-jie-ti"],
    synopsis:
      "都市商战情感剧，迪丽热巴饰演宋天成之女宋子涵，在家族恩怨与情感纠葛中演绎复杂人性。",
    highlights: ["宋子涵一角层次丰富", "早期都市商战题材"],
    status: "released",
  },
  {
    slug: "piaoliang-de-li-huizhen",
    title: "漂亮的李慧珍",
    titleEn: "Pretty Li Huizhen",
    type: "tv",
    year: 2017,
    role: "李慧珍",
    poster: w["piaoliang-de-li-huizhen"],
    synopsis:
      "翻拍自韩剧的都市励志爱情剧，迪丽热巴首挑大梁出演女一号李慧珍，演绎平凡女孩的逆袭成长。",
    highlights: ["首部担纲女主的都市剧", "励志成长的'真善美'女主"],
    status: "released",
  },
  {
    slug: "sannshengsanshi-shili-taohua",
    title: "三生三世十里桃花",
    titleEn: "Eternal Love",
    type: "tv",
    year: 2017,
    role: "白凤九",
    poster: w["sannshengsanshi-shili-taohua"],
    synopsis:
      "现象级仙侠剧，迪丽热巴饰演痴情灵动的青丘白凤九，'追夫三万年'的痴情演绎成为名场面，自此跻身一线。",
    highlights: ["现象级爆款，奠定一线地位", "凭白凤九获金鹰节肯定与超高人气"],
    status: "released",
    featured: true,
    airInfo: "东方卫视 · 浙江卫视 · 2017 年播出",
    cast: ["杨幂", "赵又廷", "迪丽热巴", "高伟光"],
  },
  {
    slug: "qin-shi-liren-mingyue-xin",
    title: "秦时丽人明月心",
    titleEn: "The King's Woman",
    type: "tv",
    year: 2017,
    role: "公孙丽",
    poster: w["qin-shi-liren-mingyue-xin"],
    synopsis:
      "古装剧，迪丽热巴一人撑起女主公孙丽，在乱世与家国情仇之间演绎坚韧深情的女性形象。",
    highlights: ["古装大女主", "兼具柔美与坚韧的演绎"],
    status: "released",
  },
  {
    slug: "lie-huo-ru-ge",
    title: "烈火如歌",
    titleEn: "The Flame's Daughter",
    type: "tv",
    year: 2018,
    role: "烈如歌",
    poster: w["lie-huo-ru-ge"],
    synopsis:
      "古装武侠言情剧，迪丽热巴饰演侠肝义胆的烈如歌，于江湖恩怨与多角情感中诠释洒脱与深情。",
    highlights: ["武侠言情大女主", "'歌歌'侠气十足"],
    status: "released",
  },
  {
    slug: "yi-qian-ling-yi-ye",
    title: "一千零一夜",
    titleEn: "Sweet Dreams",
    type: "tv",
    year: 2018,
    role: "凌凌七",
    poster: w["yi-qian-ling-yi-ye"],
    synopsis:
      "都市童话爱情剧，迪丽热巴搭档邓伦出演古灵精怪的设计师凌凌七，甜宠氛围拉满，剧中插曲与名场面广为流传。",
    highlights: ["甜宠都市剧代表作", "'七七'古灵精怪招人喜爱"],
    status: "released",
  },
  {
    slug: "san-sheng-san-shi-zhen-shang-shu",
    title: "三生三世枕上书",
    titleEn: "Eternal Love of Dream",
    type: "tv",
    year: 2020,
    role: "白凤九",
    poster: w["san-sheng-san-shi-zhen-shang-shu"],
    synopsis:
      "《三生三世十里桃花》衍生剧，迪丽热巴再度出演青丘白凤九，与高伟光（东华帝君）演绎跨越三生三世的爱恋。",
    highlights: ["白凤九的专属续篇", "凤九帝君 CP 备受期待"],
    status: "released",
  },
  {
    slug: "xingfu-chushou-keji",
    title: "幸福，触手可及！",
    titleEn: "Love Designer",
    type: "tv",
    year: 2020,
    role: "周放",
    poster: w["xingfu-chushou-keji"],
    synopsis:
      "都市职场爱情剧，迪丽热巴饰演独立干练的服装设计师周放，呈现都市女性在事业与爱情中的成长。",
    highlights: ["都市职场题材", "干练独立的设计师形象"],
    status: "released",
  },
  {
    slug: "chang-ge-xing",
    title: "长歌行",
    titleEn: "The Long Ballad",
    type: "tv",
    year: 2021,
    role: "李长歌",
    poster: w["chang-ge-xing"],
    synopsis:
      "改编自同名漫画的古装传奇剧，迪丽热巴出演智谋与气节兼备的大唐郡主李长歌，于家国动荡中成长，展现飒爽与担当。",
    highlights: ["古装大女主，飒爽智谋", "格局开阔的家国叙事"],
    status: "released",
    featured: true,
    airInfo: "腾讯视频 · 2021 年播出",
    cast: ["迪丽热巴", "吴磊", "刘宇宁"],
  },
  {
    slug: "ni-shi-wo-de-rongyao",
    title: "你是我的荣耀",
    titleEn: "You Are My Glory",
    type: "tv",
    year: 2021,
    role: "乔晶晶",
    poster: w["ni-shi-wo-de-rongyao"],
    synopsis:
      "改编自顾漫小说的都市爱情剧，迪丽热巴搭档杨洋，饰演当红明星乔晶晶，与航天工程师于途重逢相爱，'追星'与航天梦交织，甜度与口碑双高。",
    highlights: ["顾漫 IP + 航天主题", "口碑收视双丰收的国民甜剧"],
    status: "released",
    featured: true,
    airInfo: "腾讯视频 · 2021 年播出",
    cast: ["迪丽热巴", "杨洋", "潘粤明"],
  },
  {
    slug: "yu-jiao-ji",
    title: "与君初相识·恰似故人归",
    titleEn: "The Blue Whisper",
    type: "tv",
    year: 2022,
    role: "纪云禾",
    poster: w["yu-jiao-ji"],
    synopsis:
      "改编自《驭鲛记》的古装仙侠剧（分《与君初相识》《恰似故人归》两部播出），迪丽热巴饰演驭鲛人的纪云禾，演绎隐忍坚韧、爱恨交织的虐恋。",
    highlights: ["《驭鲛记》改编", "纪云禾的隐忍与成长"],
    status: "released",
  },
  {
    slug: "gong-su",
    title: "公诉",
    titleEn: "The Prosecution",
    type: "tv",
    year: 2023,
    role: "安旎",
    poster: w["gong-su"],
    synopsis:
      "现实题材法治剧，迪丽热巴出演检察官安旎，聚焦网络犯罪与公益诉讼，是其向现实主义题材转型的重要作品。",
    highlights: ["现实题材转型之作", "检察官'安旎'专业飒爽"],
    status: "released",
  },
  {
    slug: "an-le-zhuan",
    title: "安乐传",
    titleEn: "The Legend of Anle",
    type: "tv",
    year: 2023,
    role: "帝梓元 / 任安乐",
    poster: w["an-le-zhuan"],
    synopsis:
      "古装传奇剧，迪丽热巴一人分饰帝梓元与任安乐，于权谋与江湖之间演绎复仇、成长与家国情怀。",
    highlights: ["古装大女主，一人双面", "权谋与情义交织"],
    status: "released",
  },
  {
    slug: "li-jian-mei-gui",
    title: "利剑·玫瑰",
    titleEn: "Sword Rose",
    type: "tv",
    year: 2025,
    role: "邓妍",
    poster: w["li-jian-mei-gui"],
    synopsis:
      "现实题材刑侦剧，取材打拐题材，迪丽热巴饰演刑警邓妍，深入演绎一线女警的坚韧与温度，于央视八套黄金档播出，是其现实主义路线的又一力作。",
    highlights: ["央视八套黄金档", "现实打拐题材，女警'邓妍'"],
    status: "released",
    featured: true,
    airInfo: "央视八套黄金档 · 2025 年播出",
    cast: ["迪丽热巴", "金世佳", "尤勇智"],
  },
  {
    slug: "xiao-qi-qing-rang",
    title: "枭起青壤",
    titleEn: "Love on the Turquoise Land",
    type: "tv",
    year: 2025,
    role: "聂九罗",
    poster: w["xiao-qi-qing-rang"],
    synopsis:
      "古装奇幻冒险剧，迪丽热巴搭档陈星旭出演聂九罗，于神秘古域与志怪传说中展开探险与情感故事。",
    highlights: ["古装奇幻冒险题材", "聂九罗的飒与媚"],
    status: "released",
    airInfo: "腾讯视频 · 2025 年 11 月播出",
    cast: ["迪丽热巴", "陈星旭", "张俪"],
  },
  {
    slug: "bai-ri-ti-deng",
    title: "白日提灯",
    titleEn: "Love Under the Lantern",
    type: "tv",
    year: 2026,
    role: "贺思慕",
    poster: w["bai-ri-ti-deng"],
    synopsis:
      "古装奇幻爱情剧（改编自黎青燃同名小说，曾用名《慕胥辞》），迪丽热巴饰演活了四百年、天生缺失五感的归墟鬼王贺思慕，与陈飞宇饰演的少年将军段胥因五感互通而命理相连，在权谋与试探中展开禁忌之恋。",
    highlights: ["一人分饰鬼王 / 贺小小等多重状态", "东方奇幻美学与五感互通设定"],
    status: "released",
    featured: true,
    airInfo: "腾讯视频 · 2026 年 3 月 28 日开播",
    cast: ["迪丽热巴", "陈飞宇", "魏哲鸣", "张俪"],
  },
  {
    slug: "sui-ran-bu-neng-yiqie",
    title: "虽然不能同时拥有一切",
    titleEn: "Although You Can't Have Everything at Once",
    type: "tv",
    year: 2026,
    role: "卫蓝（双生）",
    poster: w["sui-ran-bu-neng-yiqie"],
    synopsis:
      "爱奇艺「微尘剧场」6 集都市奇幻迷你剧，改编自山本文绪小说《蓝，另一种蓝》。迪丽热巴一人分饰命运交错的两个卫蓝——精英作家与小镇主妇，因奇幻际遇互换人生，探讨选择与自我觉醒。",
    highlights: ["一人分饰双生卫蓝", "爱奇艺微尘剧场独播", "导演吴辰珵 · 搭档陈昊森"],
    status: "upcoming",
    featured: true,
    airInfo: "爱奇艺 · 2026 年待播（以平台官宣为准）",
    airInfoEn: "iQiyi Micro Drama · 2026 premiere TBA (subject to official announcement)",
    countdownTarget: "2026-09-01",
    countdownApproximate: true,
    cast: ["迪丽热巴", "陈昊森", "严屹宽", "叶童"],
  },
  {
    slug: "jiu-chong-tian",
    title: "九重天",
    titleEn: "Nine Heavens",
    type: "tv",
    year: 2026,
    role: "单元女主",
    poster: w["jiu-chong-tian"],
    synopsis:
      "腾讯视频 S+ 民国悬疑单元剧，九个独立故事串联，以清末民初福建闽西琉璃寨土楼为舞台。迪丽热巴于 2026 年 1 月进组拍摄民国单元戏份，搭档尹昉；具体角色名以官方公布为准。",
    highlights: ["单元叙事结构", "民国悬疑题材", "2026 年拍摄中"],
    status: "upcoming",
    airInfo: "腾讯视频 · 拍摄中",
    airInfoEn: "Tencent Video · in production",
    cast: ["迪丽热巴", "尹昉"],
  },

  // ===== 电影 =====
  {
    slug: "peng-ran-xing-dong",
    title: "怦然星动",
    titleEn: "Fall in Love Like a Star",
    type: "film",
    year: 2015,
    role: "郝美丽",
    poster: w["peng-ran-xing-dong"],
    synopsis:
      "都市爱情电影，迪丽热巴在片中出演角色郝美丽，是其早期参演的大银幕作品之一。",
    highlights: ["早期大银幕尝试", "搭档杨幂、陈学冬"],
    status: "released",
  },
  {
    slug: "aojiao-yu-pianjian",
    title: "傲娇与偏见",
    titleEn: "Pride and Prejudice",
    type: "film",
    year: 2017,
    role: "唐楠楠",
    poster: w["aojiao-yu-pianjian"],
    synopsis:
      "都市爱情喜剧电影，迪丽热巴搭档张云龙出演女主唐楠楠，演绎欢喜冤家式的甜趣爱情。",
    highlights: ["首次主演院线爱情喜剧"],
    status: "released",
  },
  {
    slug: "jie-you-zahuodian",
    title: "解忧杂货店",
    titleEn: "Namiya",
    type: "film",
    year: 2017,
    role: "彤彤",
    poster: w["jie-you-zahuodian"],
    synopsis:
      "改编自东野圭吾同名小说的治愈系电影，迪丽热巴与王俊凯、董子健等合作，在跨越时空的来信中传递温暖与善意。",
    highlights: ["东野圭吾 IP 改编", "治愈系群像"],
    status: "released",
  },
  {
    slug: "er-shi-yi-ke-la",
    title: "21克拉",
    titleEn: "21 Karat",
    type: "film",
    year: 2018,
    role: "刘佳音",
    poster: w["er-shi-yi-ke-la"],
    synopsis:
      "都市爱情喜剧电影，迪丽热巴出演节俭务实的女主刘佳音，以轻喜剧方式探讨爱情与金钱观。",
    highlights: ["轻喜剧女主", "搭档郭京飞"],
    status: "released",
  },
  {
    slug: "ri-yue",
    title: "日月",
    titleEn: "Saga of Light",
    type: "film",
    year: 2019,
    role: "嫦娥",
    poster: w["ri-yue"],
    synopsis:
      "神话爱情电影，迪丽热巴搭档窦骁，饰演热爱自然、崇尚自由的新版嫦娥；影片已官宣多年，上映信息以官方公布为准。",
    highlights: ["神话改编", "搭档窦骁"],
    status: "upcoming",
    airInfo: "上映信息待官宣",
    airInfoEn: "Release date TBA",
  },
  {
    slug: "shaolin-nvzu",
    title: "少林女足",
    titleEn: "Shaolin Women's Soccer",
    type: "film",
    year: 2025,
    role: "钰珑",
    poster: w["shaolin-nvzu"],
    synopsis:
      "周星驰导演作品（上映片名《功夫女足》），迪丽热巴饰演前锋钰珑（8 号），融合功夫与女子足球元素；已定档 2026 年 7 月 11 日全国上映。",
    synopsisEn:
      "Stephen Chow-directed film (release title Kung Fu Women's Soccer) — Dilraba as forward Yu Long (#8); kung fu meets women's soccer, opening July 11, 2026 nationwide.",
    highlights: ["周星驰导演", "功夫足球题材", "定档 7 月 11 日"],
    highlightsEn: ["Directed by Stephen Chow", "Kung fu soccer", "Opens July 11"],
    airInfo: "2026 年 7 月 11 日全国上映",
    airInfoEn: "Nationwide release July 11, 2026",
    status: "upcoming",
    countdownTarget: "2026-07-11",
    countdownApproximate: false,
  },

  // ===== 综艺 =====
  {
    slug: "pao-pao",
    title: "奔跑吧（第五季）",
    titleEn: "Keep Running S5",
    type: "variety",
    year: 2017,
    role: "常驻成员",
    poster: w["pao-pao"],
    synopsis:
      "迪丽热巴曾作为《奔跑吧》常驻成员之一参与录制，活泼可爱、热情拼搏的表现圈粉无数。",
    highlights: ["常驻 MC", "活力满满的'女汉子'反差"],
    status: "released",
  },
  {
    slug: "man-you-quan-shi-jie-s1",
    title: "慢游全世界 第一季",
    titleEn: "Travel Around the World S1",
    type: "variety",
    year: 2018,
    role: "固定嘉宾",
    poster: w["man-you-quan-shi-jie-s1"],
    synopsis:
      "旅行微综艺《慢游全世界》第一季固定嘉宾，以慢节奏深度体验海外城市人文与风景。",
    highlights: ["旅行微综艺", "2018 年固定嘉宾"],
    status: "released",
    airInfo: "酷燃视频 · 2018 年 8 月",
  },
  {
    slug: "ji-xian-tiao-zhan",
    title: "极限挑战（第五季）",
    titleEn: "Go Fighting! S5",
    type: "variety",
    year: 2019,
    role: "常驻成员",
    poster: w["ji-xian-tiao-zhan"],
    synopsis:
      "迪丽热巴加盟《极限挑战》第五季常驻嘉宾，与'极挑团'一同完成各类挑战，展现机敏与亲和。",
    highlights: ["常驻嘉宾", "综艺感与亲和力出圈"],
    status: "released",
  },
  {
    slug: "chuangzaoying-2019",
    title: "创造营 2019",
    titleEn: "CHUANG 2019",
    type: "variety",
    year: 2019,
    role: "教练 / 发起人",
    poster: w["chuangzaoying-2019"],
    synopsis:
      "迪丽热巴担任男团青春成长综艺《创造营 2019》发起人（班主任），陪伴学员成长，传递正能量与拼搏精神。",
    highlights: ["首次担任偶像选秀发起人"],
    status: "released",
  },
  {
    slug: "man-you-quan-shi-jie-s2",
    title: "慢游全世界 第二季",
    titleEn: "Travel Around the World S2",
    type: "variety",
    year: 2019,
    role: "固定嘉宾",
    poster: w["man-you-quan-shi-jie-s2"],
    synopsis:
      "《慢游全世界》第二季固定嘉宾，延续慢旅行方式探访海外目的地，展现松弛真实的旅行状态。",
    highlights: ["旅行微综艺", "2019 年固定嘉宾"],
    status: "released",
    airInfo: "北京卫视 · 爱奇艺 · 2019 年 10 月",
  },
  {
    slug: "huaer-yu-shaonian-silu",
    title: "花儿与少年·丝路季",
    titleEn: "Divas Hit the Road · Silk Road",
    type: "variety",
    year: 2023,
    role: "常驻嘉宾",
    poster: w["huaer-yu-shaonian-silu"],
    synopsis:
      "迪丽热巴参与旅行真人秀《花儿与少年·丝路季》，一路展现真诚、独立与照顾他人的暖心一面，沿途风光与人文相得益彰。",
    highlights: ["旅行真人秀", "真实有爱的相处方式收获好评"],
    status: "released",
  },
  {
    slug: "kaishi-tuili-ba-s2",
    title: "开始推理吧 第二季",
    titleEn: "The Detective S2",
    type: "variety",
    year: 2024,
    role: "常驻嘉宾",
    poster: w["kaishi-tuili-ba-s2"],
    synopsis:
      "迪丽热巴担任腾讯视频剧情推理真人秀《开始推理吧》第二季常驻嘉宾，于 2024 年 5 月至 7 月播出，在沉浸式剧情中烧脑推理，展现机敏与综艺感。",
    highlights: ["剧情推理真人秀", "2024 年常驻"],
    status: "released",
    airInfo: "腾讯视频 · 2024-05-02 至 2024-07-05",
  },
  {
    slug: "kaishi-tuili-ba-s3",
    title: "开始推理吧 第三季",
    titleEn: "The Detective S3",
    type: "variety",
    year: 2025,
    role: "常驻嘉宾",
    poster: w["kaishi-tuili-ba-s3"],
    synopsis:
      "迪丽热巴继续担任《开始推理吧》第三季常驻嘉宾，于 2025 年 5 月至 7 月播出，延续剧情推理与角色扮演的综艺模式。",
    highlights: ["剧情推理真人秀", "2025 年常驻"],
    status: "released",
    airInfo: "腾讯视频 · 2025-05-01 至 2025-07-04",
  },
];
